logging:
  root:
    level: DEBUG

dossier.store:
  feature_indexes: ['phone', 'email', 'bowNP_sip', 'region', 'image_url']

dossier.models:
  tfidf_path: /background-50000.tfidf

kvlayer:
  app_name: dossierstack
  namespace: demo
  storage_type: filestorage
  filename: /demo.db
  storage_addresses: []
